In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

from scipy import stats

In [2]:
a1 = pd.read_excel('C:/Users/윤후/Downloads/2017-2021 OECD 국가 교통사고 비교.xls')
display(a1)

,국가,2017,Unnamed: 2,Unnamed: 3,Unnamed: 4,2018,Unnamed: 6,Unnamed: 7,Unnamed: 8,2019,...,Unnamed: 11,Unnamed: 12,2020,Unnamed: 14,Unnamed: 15,Unnamed: 16,2021,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,국가,인구수(천명),자동차등록대수(천대),사고[건],사망[명],인구수(천명),자동차등록대수(천대),사고[건],사망[명],인구수(천명),...,사고[건],사망[명],인구수(천명),자동차등록대수(천대),사고[건],사망[명],인구수(천명),자동차등록대수(천대),사고[건],사망[명]
1,그리스,10692.2285,9661,10848,731,10633.2705,9522,10737,700,10574.024,...,10737,688,10512.232,9966,9083,584,10445.365,8688.323,10454,624
2,네덜란드,17207.198,11076.215,18706,535,11336.686,-,598,3.5,11553.132,...,586,3.4,11760.11,-,515,3,11958.255,-,509,2.9
3,노르웨이,5277.3925,3949.919,4086,106,5312.32,3981.143,3898,108,5348.2785,...,3579,108,5379.839,4074.86,3585,93,5403.021,4105.158,3719,80
4,뉴질랜드,4746.2515,3634.406,11245,377,4838.526,3747.29,11692,379,4959.034,...,11755,350,5061.1335,3753.96,10325,317,5129.7275,3853.634,10775,318
5,대한민국,51361.911,26323.316,216335,4185,51585.058,26990.456,217148,3781,51764.822,...,229600,3349,51780.579,28251.178,209654,3081,51821.669,28730.117,203130,2916
6,덴마크,5737.2845,3167,2789,175,5766.686,3231,2964,171,5795.878,...,2808,199,5825.641,3338,-,163,5854.2405,3408,-,130
7,독일,82624.374,57554.491,302656,3180,82896.6955,56459,308721,3275,83148.141,...,300143,3046,83328.9875,58158.344,264499,2719,83408.5545,59020.091,258987,2562
8,라트비아,1954.8625,-,3874,136,1935.6305,-,3973,151,1916.5555,...,3724,135,1897.052,-,3414,141,1873.919,-,3399,146
9,룩셈부르크,596.2825,466.472,955,25,607.913,482.001,947,36,619.973,...,-,22,630.3995,509.975,-,26,639.321,520.322,-,24
10,리투아니아,2904.45,1578.338,3055,191,2876.1275,1628.272,2925,173,2849.083,...,3188,186,2820.2665,1792.97,2788,175,2786.6505,1859.48,2784,148
11,멕시코,122839.2575,45854,11883,15865,124013.8615,47784,12237,15574,125085.3105,...,12056,14673,125998.3015,50348,11449,13630,126705.138,0,-,-
12,미국,329791.2305,290335.891,6452598,37473,332140.0375,297036.214,6734681,36835,334319.6705,...,6756084,36355,335942.0035,297100.832,5251006,39007,336997.624,302722.453,6102936,42939
13,벨기에,11384.4895,7419.405,38025,609,11448.5955,7533.172,38453,604,11510.568,...,37719,644,11561.7165,7651.138,30251,499,11611.4195,7751.422,34660,516
14,스웨덴,10058.19,6274.884,14849,252,10162.298,6331.378,14233,324,10267.9215,...,13684,221,10368.9695,6453.721,12243,204,10467.097,6537.032,12625,210
15,스위스,8451.687,6241.128,17799,230,8514.434,6315.058,18033,233,8575.5885,...,17761,187,8638.613,6469.952,16897,227,8691.4065,6584.125,17436,200
16,스페인,46584.1695,34890.527,102233,1830,46792.043,35663.427,102299,1806,47131.372,...,104080,1755,47363.807,36656.957,72959,1370,47486.935,37046.864,-,1533
17,슬로바키아,5439.4165,-,5638,276,5446.7455,-,5689,260,5453.924,...,5410,270,5456.6805,-,4555,247,5447.622,-,4541,247
18,슬로베니아,2098.392,1423.819,6185,104,2105.924,1477.215,6014,91,2112.9015,...,6025,102,2117.641,1555.168,4780,80,2119.4095,1564.581,5330,114
19,아이슬란드,343.632,324,952,16,352.946,337,868,18,360.7745,...,770,6,366.669,343,727,8,370.335,351,873,9
20,아일랜드,4771.8535,2684.73,6077,154,4834.507,2729.001,6056,134,4896.019,...,5819,140,4946.119,2848.023,4428,146,4986.526,2901.404,4913,136
21,에스토니아,1317.5485,-,1406,48,1322.1475,-,1469,67,1327.0385,...,1406,52,1329.444,-,1368,60,1328.701,-,1568,55
22,영국,66064.8045,38892.992,136063,1856,66432.9935,39365.027,128384,1839,66778.659,...,123212,1808,67059.474,39800.924,95422,1516,67281.0395,40274.822,105791,1608
23,오스트리아,8797.496,6654.504,37402,414,8840.5125,6771.395,36846,409,8879.9395,...,35736,416,8907.777,6996.222,30670,344,8922.082,7098.814,32774,362
24,이스라엘,8309.257,3373.139,13628,364,8456.483,3495.412,12557,316,8607.9195,...,12670,355,8757.4895,3689.299,10836,305,8900.059,3840.104,11554,364
25,이탈리아,60004.032,53539.347,174933,3378,59877.4255,54256.37,172344,3334,59727.932,...,172183,3173,59500.5785,55377.339,118298,2395,59240.3295,56091.011,151875,2875
26,일본,126662.472,91404.412,472165,4431,126255.866,91468.471,430601,4166,125791.6765,...,381237,3920,125244.7605,91430.489,309178,3416,124612.5305,91253.654,305196,3205
27,체코,10531.305,7107,21263,577,10534.593,7386,21889,658,10536.871,...,20806,617,10530.9535,7863,18419,517,10510.7505,8026,18156,531
28,칠레,18368.577,5079.718,41743,1925,18701.4505,5382.604,39194,1955,19039.4855,...,39246,1973,19300.3145,5479.286,28870,1794,19493.1845,5980.693,35530,2052
29,캐나다,36554.3475,24618.831,114412,1861,37035.254,25043.044,111334,1939,37522.5845,...,104640,1756,37888.705,25744.196,79990,1746,38155.012,26223.871,79563,1768
30,코스타리카,4993.8415,2277.65,-,862,5040.734,2396.091,-,811,5084.5315,...,-,787,5123.105,2553.023,-,570,5153.957,2631.2,-,707
31,콜롬비아,48351.6705,13673.677,-,6505,49276.9615,14446.084,-,6629,50187.4065,...,-,6577,50930.6625,15977.108,-,5447,51516.562,16712.446,-,7238
32,튀르키예,82089.8265,-,182669,7427,82809.3045,-,186832,6675,83481.684,...,174896,5473,84135.4275,-,-,4866,84775.4035,-,-,5362
33,포르투갈,10307.53,6164.7,34416,602,10289.835,-,35802,675,10289.923,...,37256,683,10298.1915,-,27725,535,10290.103,-,-,561
34,폴란드,38532.812,29635,32760,2831,38521.4565,30801,31674,2859,38493.601,...,30288,2904,38428.3665,32991,23540,2491,38307.7255,34030,22816,2245
35,프랑스,64144.0865,47393.753,58613,3448,64277.8075,48341.25,55766,3248,64399.7585,...,56016,3244,64480.053,48197.301,45121,2541,64531.444,48542.122,53540,2944
36,핀란드,5508.1395,4661,4432,238,5515.461,4766,4312,239,5521.5365,...,4002,211,5529.468,4968.156,3608,223,5535.992,5028.385,3243,225
37,헝가리,9788.941,4211.711,16489,625,9776.3575,4417.848,16951,633,9771.7955,...,16627,602,9750.5725,4756.537,13778,460,9709.786,4885.598,14233,544
38,호주,24590.3335,18781.204,-,1223,24979.23,19173.279,-,1135,25357.17,...,-,1187,25670.0505,19805.331,-,1097,25921.089,20267.832,-,1116

In [3]:
import pandas as pd

# 파일 불러오기 (1행은 진짜 컬럼명 아님, 2행이 컬럼명임)
df_raw = pd.read_excel("C:/Users/윤후/Downloads/2017-2021 OECD 국가 교통사고 비교.xls", header=[0, 1])

# 열 이름 조합해서 보기 좋게 변경 (예: 2017 인구수(천명) → '2017_인구수(천명)')
df_raw.columns = [f"{col[0]}_{col[1]}" if 'Unnamed' not in col[1] else col[0] for col in df_raw.columns]

# 결과 확인
df_raw

,국가_국가,2017_인구수(천명),2017_자동차등록대수(천대),2017_사고[건],2017_사망[명],2018_인구수(천명),2018_자동차등록대수(천대),2018_사고[건],2018_사망[명],2019_인구수(천명),...,2019_사고[건],2019_사망[명],2020_인구수(천명),2020_자동차등록대수(천대),2020_사고[건],2020_사망[명],2021_인구수(천명),2021_자동차등록대수(천대),2021_사고[건],2021_사망[명]
0,그리스,10692.2285,9661,10848,731,10633.2705,9522,10737,700.0,10574.0240,...,10737,688.0,10512.2320,9966,9083,584,10445.3650,8688.323,10454,624
1,네덜란드,17207.1980,11076.215,18706,535,11336.6860,-,598,3.5,11553.1320,...,586,3.4,11760.1100,-,515,3,11958.2550,-,509,2.9
2,노르웨이,5277.3925,3949.919,4086,106,5312.3200,3981.143,3898,108.0,5348.2785,...,3579,108.0,5379.8390,4074.86,3585,93,5403.0210,4105.158,3719,80
3,뉴질랜드,4746.2515,3634.406,11245,377,4838.5260,3747.29,11692,379.0,4959.0340,...,11755,350.0,5061.1335,3753.96,10325,317,5129.7275,3853.634,10775,318
4,대한민국,51361.9110,26323.316,216335,4185,51585.0580,26990.456,217148,3781.0,51764.8220,...,229600,3349.0,51780.5790,28251.178,209654,3081,51821.6690,28730.117,203130,2916
5,덴마크,5737.2845,3167,2789,175,5766.6860,3231,2964,171.0,5795.8780,...,2808,199.0,5825.6410,3338,-,163,5854.2405,3408,-,130
6,독일,82624.3740,57554.491,302656,3180,82896.6955,56459,308721,3275.0,83148.1410,...,300143,3046.0,83328.9875,58158.344,264499,2719,83408.5545,59020.091,258987,2562
7,라트비아,1954.8625,-,3874,136,1935.6305,-,3973,151.0,1916.5555,...,3724,135.0,1897.0520,-,3414,141,1873.9190,-,3399,146
8,룩셈부르크,596.2825,466.472,955,25,607.9130,482.001,947,36.0,619.9730,...,-,22.0,630.3995,509.975,-,26,639.3210,520.322,-,24
9,리투아니아,2904.4500,1578.338,3055,191,2876.1275,1628.272,2925,173.0,2849.0830,...,3188,186.0,2820.2665,1792.97,2788,175,2786.6505,1859.48,2784,148
10,멕시코,122839.2575,45854,11883,15865,124013.8615,47784,12237,15574.0,125085.3105,...,12056,14673.0,125998.3015,50348,11449,13630,126705.1380,0,-,-
11,미국,329791.2305,290335.891,6452598,37473,332140.0375,297036.214,6734681,36835.0,334319.6705,...,6756084,36355.0,335942.0035,297100.832,5251006,39007,336997.6240,302722.453,6102936,42939
12,벨기에,11384.4895,7419.405,38025,609,11448.5955,7533.172,38453,604.0,11510.5680,...,37719,644.0,11561.7165,7651.138,30251,499,11611.4195,7751.422,34660,516
13,스웨덴,10058.1900,6274.884,14849,252,10162.2980,6331.378,14233,324.0,10267.9215,...,13684,221.0,10368.9695,6453.721,12243,204,10467.0970,6537.032,12625,210
14,스위스,8451.6870,6241.128,17799,230,8514.4340,6315.058,18033,233.0,8575.5885,...,17761,187.0,8638.6130,6469.952,16897,227,8691.4065,6584.125,17436,200
15,스페인,46584.1695,34890.527,102233,1830,46792.0430,35663.427,102299,1806.0,47131.3720,...,104080,1755.0,47363.8070,36656.957,72959,1370,47486.9350,37046.864,-,1533
16,슬로바키아,5439.4165,-,5638,276,5446.7455,-,5689,260.0,5453.9240,...,5410,270.0,5456.6805,-,4555,247,5447.6220,-,4541,247
17,슬로베니아,2098.3920,1423.819,6185,104,2105.9240,1477.215,6014,91.0,2112.9015,...,6025,102.0,2117.6410,1555.168,4780,80,2119.4095,1564.581,5330,114
18,아이슬란드,343.6320,324,952,16,352.9460,337,868,18.0,360.7745,...,770,6.0,366.6690,343,727,8,370.3350,351,873,9
19,아일랜드,4771.8535,2684.73,6077,154,4834.5070,2729.001,6056,134.0,4896.0190,...,5819,140.0,4946.1190,2848.023,4428,146,4986.5260,2901.404,4913,136
20,에스토니아,1317.5485,-,1406,48,1322.1475,-,1469,67.0,1327.0385,...,1406,52.0,1329.4440,-,1368,60,1328.7010,-,1568,55
21,영국,66064.8045,38892.992,136063,1856,66432.9935,39365.027,128384,1839.0,66778.6590,...,123212,1808.0,67059.4740,39800.924,95422,1516,67281.0395,40274.822,105791,1608
22,오스트리아,8797.4960,6654.504,37402,414,8840.5125,6771.395,36846,409.0,8879.9395,...,35736,416.0,8907.7770,6996.222,30670,344,8922.0820,7098.814,32774,362
23,이스라엘,8309.2570,3373.139,13628,364,8456.4830,3495.412,12557,316.0,8607.9195,...,12670,355.0,8757.4895,3689.299,10836,305,8900.0590,3840.104,11554,364
24,이탈리아,60004.0320,53539.347,174933,3378,59877.4255,54256.37,172344,3334.0,59727.9320,...,172183,3173.0,59500.5785,55377.339,118298,2395,59240.3295,56091.011,151875,2875
25,일본,126662.4720,91404.412,472165,4431,126255.8660,91468.471,430601,4166.0,125791.6765,...,381237,3920.0,125244.7605,91430.489,309178,3416,124612.5305,91253.654,305196,3205
26,체코,10531.3050,7107,21263,577,10534.5930,7386,21889,658.0,10536.8710,...,20806,617.0,10530.9535,7863,18419,517,10510.7505,8026,18156,531
27,칠레,18368.5770,5079.718,41743,1925,18701.4505,5382.604,39194,1955.0,19039.4855,...,39246,1973.0,19300.3145,5479.286,28870,1794,19493.1845,5980.693,35530,2052
28,캐나다,36554.3475,24618.831,114412,1861,37035.2540,25043.044,111334,1939.0,37522.5845,...,104640,1756.0,37888.7050,25744.196,79990,1746,38155.0120,26223.871,79563,1768
29,코스타리카,4993.8415,2277.65,-,862,5040.7340,2396.091,-,811.0,5084.5315,...,-,787.0,5123.1050,2553.023,-,570,5153.9570,2631.2,-,707
30,콜롬비아,48351.6705,13673.677,-,6505,49276.9615,14446.084,-,6629.0,50187.4065,...,-,6577.0,50930.6625,15977.108,-,5447,51516.5620,16712.446,-,7238
31,튀르키예,82089.8265,-,182669,7427,82809.3045,-,186832,6675.0,83481.6840,...,174896,5473.0,84135.4275,-,-,4866,84775.4035,-,-,5362
32,포르투갈,10307.5300,6164.7,34416,602,10289.8350,-,35802,675.0,10289.9230,...,37256,683.0,10298.1915,-,27725,535,10290.1030,-,-,561
33,폴란드,38532.8120,29635,32760,2831,38521.4565,30801,31674,2859.0,38493.6010,...,30288,2904.0,38428.3665,32991,23540,2491,38307.7255,34030,22816,2245
34,프랑스,64144.0865,47393.753,58613,3448,64277.8075,48341.25,55766,3248.0,64399.7585,...,56016,3244.0,64480.0530,48197.301,45121,2541,64531.4440,48542.122,53540,2944
35,핀란드,5508.1395,4661,4432,238,5515.4610,4766,4312,239.0,5521.5365,...,4002,211.0,5529.4680,4968.156,3608,223,5535.9920,5028.385,3243,225
36,헝가리,9788.9410,4211.711,16489,625,9776.3575,4417.848,16951,633.0,9771.7955,...,16627,602.0,9750.5725,4756.537,13778,460,9709.7860,4885.598,14233,544
37,호주,24590.3335,18781.204,-,1223,24979.2300,19173.279,-,1135.0,25357.1700,...,-,1187.0,25670.0505,19805.331,-,1097,25921.0890,20267.832,-,1116

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. 데이터를 길게 변환
df_melted = df.melt(id_vars=['국가_국가'], var_name='항목', value_name='값')
df_melted[['연도', '지표']] = df_melted['항목'].str.extract(r'(\d{4})_(.+)')
df_melted['값'] = pd.to_numeric(df_melted['값'], errors='coerce')

# 2. 피벗 테이블로 인구/사고/사망 나누기
df_pivot = df_melted.pivot_table(index=['국가_국가', '연도'], columns='지표', values='값').reset_index()

# 3. 사고율/사망률 계산
df_pivot['사고율'] = df_pivot['사고[건]'] / df_pivot['인구수(천명)']
df_pivot['사망률'] = df_pivot['사망[명]'] / df_pivot['인구수(천명)']

# 모든 행 보기
pd.set_option('display.max_rows', None) 

# 모든 열 보기
pd.set_option('display.max_columns', None)  # 모든 열 보기

# 또는 print(df_pivot)
df_pivot

NameError: name 'df' is not defined

In [ ]:
df_pivot.to_csv('사고율_사망률_테이블.csv', index=False)